name: venure
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  multi_select_flutter: ^4.1.3
  uuid: ^4.5.1
  dartz: ^0.10.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  image_picker: ^1.1.2
  awesome_dio_interceptor: ^1.3.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1
  json_serializable: 6.9.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  cached_network_image: ^3.4.1
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.1
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/animation/

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dosis-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Dosis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dosis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dosis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dosis-Light.ttf
          weight: 300
        - asset: assets/fonts/Dosis-ExtraLight.ttf
          weight: 200
